name: build-docker

on:
  push:
    branches:
      - "build"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile.base
          push: false
          tags: outlinewiki/outline-base:latest
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: frankli0324/outline:latest
